
WORLD_BG = "#333333"
OPTIONS_BG = "#666666"

WIDTH = 800  # px
HEIGHT = 600  # px

WORLD_HEIGHT = 400  # px
OPTIONS_HEIGHT = 200  # px

POSITION_WIDTH = 40  # px
POSITION_HEIGHT = 40  # px
POSITION_BORDER_WIDTH = 1  # px
POSITION_BORDER_COLOR = "black"
POSITION_BG = "#dddddd"
POSITION_BG_WALL = "#222222"
POSITION_BG_GOAL = "#ddffdd"
POSITION_BG_DANGER = "#ffdddd"
